### ISSUE TITLE
Fails on Mac OS 10.13.6

### ISSUE THREAD

**Issue by steeley** [philhartung/aes67-monitor#4]
npm install produces the error below:
```
ninja: build stopped: subcommand failed.
ERR! OMG Process terminated: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! audify@1.5.2 rebuild: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the audify@1.5.2 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2021-04-14T20_20_44_307Z-debug.log
npm WARN aes67-monitor@0.2.0 No repository field.
npm WARN aes67-monitor@0.2.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! audify@1.5.2 install: `prebuild-install || npm run rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the audify@1.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2021-04-14T20_20_45_048Z-debug.log
```

The end of the log shows:

```
866 warn aes67-monitor@0.2.0 No repository field.
3867 warn aes67-monitor@0.2.0 No license field.
3868 verbose stack Error: audify@1.5.2 install: `prebuild-install || npm run rebuild`
3868 verbose stack Exit status 1
3868 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3868 verbose stack     at EventEmitter.emit (events.js:315:20)
3868 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3868 verbose stack     at ChildProcess.emit (events.js:315:20)
3868 verbose stack     at maybeClose (internal/child_process.js:1048:16)
3868 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
3869 verbose pkgid audify@1.5.2
3870 verbose cwd /Users/ian/aes67-monitor
3871 verbose Darwin 17.7.0
3872 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3873 verbose node v14.16.1
3874 verbose npm  v6.14.12
3875 error code ELIFECYCLE
3876 error errno 1
3877 error audify@1.5.2 install: `prebuild-install || npm run rebuild`
3877 error Exit status 1
3878 error Failed at the audify@1.5.2 install script.
3878 error This is probably not a problem with npm. There is likely additional logging output above.
3879 verbose exit [ 1, true ]
```

**Comment by philhartung** [comment]
From the output it looks like there is no prebuilt binary of [Audify](https://github.com/almoghamdani/audify) for your system. Audify is the library I use for interfacing with the audio APIs on different operating systems. Please make sure you have all requirements for building from source installed (see https://github.com/almoghamdani/audify#requirements-for-source-build):
- Node or Electron versions that support N-API 5 and up
- CMake
- Clang or GCC
- Ninja or Make (Ninja will be picked if both present)

**Comment by steeley** [comment]
thanks -  it seems audify install is failing with many issues.
I am going back to using only Dante -  AES67 is too much of an experiment at the moment.
