### ISSUE TITLE
failing installation : electron

### ISSUE THREAD

**Issue by FplusOlivier** [philhartung/aes67-monitor#5]
Hello,
Trying to install it, I get this error when "npm start"
`> aes67-monitor@0.2.0 start /home/stream/Téléchargements/aesmonit/aes67-monitor
> electron .

/home/stream/Téléchargements/aesmonit/aes67-monitor/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/stream/Téléchargements/aesmonit/aes67-monitor/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/stream/Téléchargements/aesmonit/aes67-monitor/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/stream/Téléchargements/aesmonit/aes67-monitor/node_modules/electron/cli.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aes67-monitor@0.2.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aes67-monitor@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T13_00_19_037Z-debug.log
`
Could you please help me?
I'm on ubuntu 20.04
Many thanks

**Comment by philhartung** [comment]
From the npm output it looks like Electron didn't install correctly. The installation of Electron might fail when there is a bad internet connection. Can you please try to reinstall all dependencies (execute these command in the _aes67-monitor_ directory):
```
rm -r node_modules/
npm install
```
after that you should be able to run `npm start`. If it still fails with the same error it would be helpful if you would send me the output of `npm install` to see why the installation is failing.
